name: CI
on: [pull_request]

jobs:
    quality:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [14.10]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm
                key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                  ${{ runner.OS }}-node-
                  ${{ runner.OS }}-

            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm lint
              
            - name: Run tests
              run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

            - name: Code Coverage
              run: ng test --no-watch --code-coverage

            - name: SonarCloud scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}